FROM pytorch/pytorch
ENV DOCKER_RUNNING=True
ENV MQTT_IP=10.24.24.32 MQTT_PORT=1884
ENV REDIS_IP=10.24.24.32 REDIS_PORT=6379
ENV GRPC_TIMEOUT=360
WORKDIR /src
COPY src/server/requirements.txt .
RUN python -m pip install -r requirements.txt
COPY docker/server_entrypoint.sh .
COPY src .
CMD ["bash", "./server_entrypoint.sh"]

