# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import grpc_pb2 as proto_dot_grpc__pb2


class EdgeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Echo = channel.unary_unary(
                '/EdgeService/Echo',
                request_serializer=proto_dot_grpc__pb2.echoMessage.SerializeToString,
                response_deserializer=proto_dot_grpc__pb2.echoMessage.FromString,
                )
        self.InitBench = channel.unary_unary(
                '/EdgeService/InitBench',
                request_serializer=proto_dot_grpc__pb2.InitBenchRequest.SerializeToString,
                response_deserializer=proto_dot_grpc__pb2.InitBenchResponse.FromString,
                )
        self.StartTraining = channel.unary_unary(
                '/EdgeService/StartTraining',
                request_serializer=proto_dot_grpc__pb2.InitTrainRequest.SerializeToString,
                response_deserializer=proto_dot_grpc__pb2.InitTrainResponse.FromString,
                )
        self.StreamFile = channel.stream_unary(
                '/EdgeService/StreamFile',
                request_serializer=proto_dot_grpc__pb2.UploadFile.SerializeToString,
                response_deserializer=proto_dot_grpc__pb2.StringResponse.FromString,
                )
        self.StartValidation = channel.unary_unary(
                '/EdgeService/StartValidation',
                request_serializer=proto_dot_grpc__pb2.InitValidationRequest.SerializeToString,
                response_deserializer=proto_dot_grpc__pb2.InitValidationResponse.FromString,
                )
        self.StartInference = channel.unary_unary(
                '/EdgeService/StartInference',
                request_serializer=proto_dot_grpc__pb2.InferenceRequest.SerializeToString,
                response_deserializer=proto_dot_grpc__pb2.InferenceResponse.FromString,
                )
        self.ResetDetector = channel.unary_unary(
                '/EdgeService/ResetDetector',
                request_serializer=proto_dot_grpc__pb2.ResetDetectorRequest.SerializeToString,
                response_deserializer=proto_dot_grpc__pb2.ResetDetectorResponse.FromString,
                )


class EdgeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Echo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitBench(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartTraining(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamFile(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartValidation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartInference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetDetector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EdgeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Echo': grpc.unary_unary_rpc_method_handler(
                    servicer.Echo,
                    request_deserializer=proto_dot_grpc__pb2.echoMessage.FromString,
                    response_serializer=proto_dot_grpc__pb2.echoMessage.SerializeToString,
            ),
            'InitBench': grpc.unary_unary_rpc_method_handler(
                    servicer.InitBench,
                    request_deserializer=proto_dot_grpc__pb2.InitBenchRequest.FromString,
                    response_serializer=proto_dot_grpc__pb2.InitBenchResponse.SerializeToString,
            ),
            'StartTraining': grpc.unary_unary_rpc_method_handler(
                    servicer.StartTraining,
                    request_deserializer=proto_dot_grpc__pb2.InitTrainRequest.FromString,
                    response_serializer=proto_dot_grpc__pb2.InitTrainResponse.SerializeToString,
            ),
            'StreamFile': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamFile,
                    request_deserializer=proto_dot_grpc__pb2.UploadFile.FromString,
                    response_serializer=proto_dot_grpc__pb2.StringResponse.SerializeToString,
            ),
            'StartValidation': grpc.unary_unary_rpc_method_handler(
                    servicer.StartValidation,
                    request_deserializer=proto_dot_grpc__pb2.InitValidationRequest.FromString,
                    response_serializer=proto_dot_grpc__pb2.InitValidationResponse.SerializeToString,
            ),
            'StartInference': grpc.unary_unary_rpc_method_handler(
                    servicer.StartInference,
                    request_deserializer=proto_dot_grpc__pb2.InferenceRequest.FromString,
                    response_serializer=proto_dot_grpc__pb2.InferenceResponse.SerializeToString,
            ),
            'ResetDetector': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetDetector,
                    request_deserializer=proto_dot_grpc__pb2.ResetDetectorRequest.FromString,
                    response_serializer=proto_dot_grpc__pb2.ResetDetectorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'EdgeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EdgeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Echo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/EdgeService/Echo',
            proto_dot_grpc__pb2.echoMessage.SerializeToString,
            proto_dot_grpc__pb2.echoMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InitBench(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/EdgeService/InitBench',
            proto_dot_grpc__pb2.InitBenchRequest.SerializeToString,
            proto_dot_grpc__pb2.InitBenchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartTraining(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/EdgeService/StartTraining',
            proto_dot_grpc__pb2.InitTrainRequest.SerializeToString,
            proto_dot_grpc__pb2.InitTrainResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/EdgeService/StreamFile',
            proto_dot_grpc__pb2.UploadFile.SerializeToString,
            proto_dot_grpc__pb2.StringResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartValidation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/EdgeService/StartValidation',
            proto_dot_grpc__pb2.InitValidationRequest.SerializeToString,
            proto_dot_grpc__pb2.InitValidationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartInference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/EdgeService/StartInference',
            proto_dot_grpc__pb2.InferenceRequest.SerializeToString,
            proto_dot_grpc__pb2.InferenceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResetDetector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/EdgeService/ResetDetector',
            proto_dot_grpc__pb2.ResetDetectorRequest.SerializeToString,
            proto_dot_grpc__pb2.ResetDetectorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class DiscoveryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/DiscoveryService/Register',
                request_serializer=proto_dot_grpc__pb2.ClientRegistration.SerializeToString,
                response_deserializer=proto_dot_grpc__pb2.RegistrationResponse.FromString,
                )
        self.Heartbeat = channel.stream_stream(
                '/DiscoveryService/Heartbeat',
                request_serializer=proto_dot_grpc__pb2.HeartbeatPing.SerializeToString,
                response_deserializer=proto_dot_grpc__pb2.HeartbeatPong.FromString,
                )
        self.Deregister = channel.unary_unary(
                '/DiscoveryService/Deregister',
                request_serializer=proto_dot_grpc__pb2.DeregisterRequest.SerializeToString,
                response_deserializer=proto_dot_grpc__pb2.DeregisterResponse.FromString,
                )


class DiscoveryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deregister(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiscoveryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=proto_dot_grpc__pb2.ClientRegistration.FromString,
                    response_serializer=proto_dot_grpc__pb2.RegistrationResponse.SerializeToString,
            ),
            'Heartbeat': grpc.stream_stream_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=proto_dot_grpc__pb2.HeartbeatPing.FromString,
                    response_serializer=proto_dot_grpc__pb2.HeartbeatPong.SerializeToString,
            ),
            'Deregister': grpc.unary_unary_rpc_method_handler(
                    servicer.Deregister,
                    request_deserializer=proto_dot_grpc__pb2.DeregisterRequest.FromString,
                    response_serializer=proto_dot_grpc__pb2.DeregisterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DiscoveryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DiscoveryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DiscoveryService/Register',
            proto_dot_grpc__pb2.ClientRegistration.SerializeToString,
            proto_dot_grpc__pb2.RegistrationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Heartbeat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/DiscoveryService/Heartbeat',
            proto_dot_grpc__pb2.HeartbeatPing.SerializeToString,
            proto_dot_grpc__pb2.HeartbeatPong.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Deregister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DiscoveryService/Deregister',
            proto_dot_grpc__pb2.DeregisterRequest.SerializeToString,
            proto_dot_grpc__pb2.DeregisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
